### ISSUE TITLE
Is it possible to declare an existing variable with types?

### ISSUE THREAD

**Issue by gr2m** [orta/octokit-playground#1]
Thanks again for creating this example @orta. It's still rather overwhelming but I'm amazed that it's working :D 

I wonder if it is somehow possible to define a global variable with a specific type?

E.g. instead of 

```js
import {Octokit} from "@octokit/rest"

const octokit = new Octokit()

octokit.actions.cancelWorkflowRun
```

I'd like to just type

```js
octokit.actions.cancelWorkflowRun
```

but get the same intellisense for `octokit`.

I've looked through https://www.typescriptlang.org/dev/sandbox/ and https://microsoft.github.io/monaco-editor/playground.html but couldn't find anything. Is something like that possible?

**Comment by orta** [comment]
Yep, you need to make a fake module in the virtual file system which sets up the globals

```ts
        const globalDTS = `const octokit: import("@octokit/rest").Octokit  `
        sb.languageServiceDefaults.addExtraLib(globalDTS, "file:///node_modules/@types/ambient/index.d.ts");
``` 

Added in https://github.com/orta/octokit-playground/commit/0ece0ceec66cdc17742f0b3ec7fa160b1c7888c0

To test it I re-created the vfs setup locally:

```
mkdir octotest
yarn init -y
yarn add @octokit/rest
touch index.ts

# This is how it was before
```

Then I just added a few files in the folder structure to test in vsocde what would trigger the expected behavior ( I added @types/jest and then copied their syntax)

**Comment by gr2m** [comment]
Thank you so much!!!
